CREATE SCHEMA `warehouse` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `tUSER_ROLES` (
  `USER_ROLES_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `AUTHORITY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ROLES_ID`));

CREATE TABLE `tUSER` (
  `USER_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `USER_ROLES_ID` BIGINT NOT NULL,
  PRIMARY KEY (`USER_ID`),
  INDEX `FK_USER_ROLES_TO_USER_idx` (`USER_ROLES_ID` ASC),
  CONSTRAINT `FK_USER_ROLES_TO_USER`
    FOREIGN KEY (`USER_ROLES_ID`)
    REFERENCES `warehouse`.`tuser_roles` (`USER_ROLES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `tCONTRAGENT` (
  `CONTRAGENT_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,  
  `IS_ACTIVE` BIT(1) NOT NULL DEFAULT 1,
  `CREATE_DATE` DATE NOT NULL ,
  PRIMARY KEY (`CONTRAGENT_ID`));
  
CREATE TABLE `tADDRESS` (
  `ADDRESS_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `FULLADDRESS` VARCHAR(1000) NOT NULL, 
  PRIMARY KEY (`ADDRESS_ID`));

CREATE TABLE `tCONTRAGENT_ADDRESS` (
  `CONTRAGENT_ID` BIGINT(20) NOT NULL,
  `ADDRESS_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`CONTRAGENT_ID`, `ADDRESS_ID`),
  KEY `FK_ADDRESS_TO_CONTRAGENT` (`ADDRESS_ID`),
  KEY `FK_CONTRAGENT_TO_ADDRESS` (`CONTRAGENT_ID`),
  CONSTRAINT `FK_ADDRESS_TO_CONTRAGENT` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `tADDRESS` (`ADDRESS_ID`),
  CONSTRAINT `FK_CONTRAGENT_TO_ADDRESS` FOREIGN KEY (`CONTRAGENT_ID`) REFERENCES `tCONTRAGENT` (`CONTRAGENT_ID`)
);

CREATE TABLE `tPRODUCT` (
  `PRODUCT_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `PRODUCT_TYPE` int(11) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
);

CREATE TABLE `tSTORE` (
  `STORE_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`STORE_ID`)
);

CREATE TABLE `tINCOMING` (
  `INCOMMING_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CREATE_DATE` date NOT NULL,
  `CONTRAGENT_ID` BIGINT NOT NULL,
  `PRODUCT_ID` BIGINT NOT NULL,
  `PRODUCT_COUNT` double NOT NULL,
  `STORE_ID` BIGINT NOT NULL,
  `COMMENT` VARCHAR(4000) DEFAULT NULL,
  PRIMARY KEY (`INCOMMING_ID`),
  KEY `FK_CONTRAGENT_TO_INCOMING` (`CONTRAGENT_ID`),
  KEY `FK_PRODUCT_TO_INC` (`PRODUCT_ID`),
  KEY `FK_STORE_TO_INC` (`STORE_ID`),
  CONSTRAINT `FK_CONTRAGENT_TO_INC` FOREIGN KEY (`CONTRAGENT_ID`) REFERENCES `tCONTRAGENT` (`CONTRAGENT_ID`),
  CONSTRAINT `FK_PRODUCT_TO_INC` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `tPRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_STORE_TO_INC` FOREIGN KEY (`STORE_ID`) REFERENCES `tSTORE` (`STORE_ID`)
);

CREATE TABLE `tTRANSPORT` (
  `TRANSPORT_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`TRANSPORT_ID`)
);

CREATE TABLE `tSHIPMENT` (
  `SHIPMENT_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CONTRAGENT_ID` BIGINT NOT NULL,
  `CREATE_DATE` DATE NOT NULL,
  `PRODUCT_ID` BIGINT NOT NULL,
  `PRODUCT_COUNT` DOUBLE NOT NULL,
  `STORE_ID` BIGINT NOT NULL,
  `TRANSPORT_ID` BIGINT NOT NULL,
  `ADDRESS_ID` BIGINT NOT NULL,
  `PAYMENT_TYPE` BIT(1) NOT NULL,
  `COMMENT` VARCHAR(4000) NULL,
  PRIMARY KEY (`SHIPMENT_ID`)
  KEY `IDX_CONTRAGENT_TO_SH` (`CONTRAGENT_ID`),
  KEY `IDX_PRODUCT_TO_SH` (`PRODUCT_ID`),
  KEY `IDX_STORE_TO_SH` (`STORE_ID`),
  KEY `IDX_TRANSPORT_TO_SH` (`TRANSPORT_ID`),
  KEY `IDX_ADDRESS_TO_SH` (`ADDRESS_ID`),
  CONSTRAINT `FK_CONTRAGENT_TO_SH` FOREIGN KEY (`CONTRAGENT_ID`) REFERENCES `tcontragent` (`CONTRAGENT_ID`),
  CONSTRAINT `FK_PRODUCT_TO_SH` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `tproduct` (`PRODUCT_ID`),
  CONSTRAINT `FK_STORE_TO_SH` FOREIGN KEY (`STORE_ID`) REFERENCES `tstore` (`STORE_ID`),
  CONSTRAINT `FK_TRANSPORT_TO_SH` FOREIGN KEY (`TRANSPORT_ID`) REFERENCES `ttransport` (`TRANSPORT_ID`),
  CONSTRAINT `FK_ADDRESS_TO_SH` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `taddress` (`ADDRESS_ID`)
);

CREATE TABLE `tPACKING` (
  `PAKING_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` bigint(20) NOT NULL,
  `PRODUCT_COUNT` double NOT NULL,
  `BAG_COUNT` int(11) NOT NULL,
  `BAG_RESIDUE` int(11) DEFAULT NULL,
  PRIMARY KEY (`PAKING_ID`),
  KEY `IDX_FK_PRODUCT_TO_P` (`PRODUCT_ID`),
  CONSTRAINT `FK_PRODUCT_TO_P` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `tproduct` (`PRODUCT_ID`)
);

//Добавляем мешки, все остальные типы продукта будут идти как Россыпь и неявно прописываться тип в базу.
INSERT INTO tPRODUCT (`PRODUCT_ID`, `NAME`, `PRODUCT_TYPE`) VALUES ('1', 'Мешки', '0');




