CREATE SCHEMA `warehouse` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `warehouse`.`tUSER_ROLES` (
  `USER_ROLES_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `AUTHORITY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ROLES_ID`));

CREATE TABLE `warehouse`.`tUSER` (
  `USER_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `USER_ROLES_ID` BIGINT NOT NULL,
  PRIMARY KEY (`USER_ID`),
  INDEX `FK_USER_ROLES_TO_USER_idx` (`USER_ROLES_ID` ASC),
  CONSTRAINT `FK_USER_ROLES_TO_USER`
    FOREIGN KEY (`USER_ROLES_ID`)
    REFERENCES `warehouse`.`tuser_roles` (`USER_ROLES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `warehouse`.`tCONTRAGENT` (
  `CONTRAGENT_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,  
  `IS_ACTIVE` BIT(1) NOT NULL DEFAULT 1,
  `CREATE_DATE` DATE NOT NULL ,
  PRIMARY KEY (`CONTRAGENT_ID`));
  
CREATE TABLE `warehouse`.`tADDRESS` (
  `ADDRESS_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `FULLADDRESS` VARCHAR(1000) NOT NULL, 
  PRIMARY KEY (`ADDRESS_ID`));

CREATE TABLE `warehouse`.`tCONTRAGENT_ADDRESS` (
  `CONTRAGENT_ID` BIGINT(20) NOT NULL,
  `ADDRESS_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`CONTRAGENT_ID`, `ADDRESS_ID`),
  KEY `FK_ADDRESS_TO_CONTRAGENT` (`ADDRESS_ID`),
  KEY `FK_CONTRAGENT_TO_ADDRESS` (`CONTRAGENT_ID`),
  CONSTRAINT `FK_ADDRESS_TO_CONTRAGENT` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `tADDRESS` (`ADDRESS_ID`),
  CONSTRAINT `FK_CONTRAGENT_TO_ADDRESS` FOREIGN KEY (`CONTRAGENT_ID`) REFERENCES `tCONTRAGENT` (`CONTRAGENT_ID`)
);
